# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint Check

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  lint-check:
    name: Lint Check (tsc)
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + install deps
        uses: ./.github/actions/setup-install

      - name: Lint Check
        run: npm run lint
